sudo: required
services: 
  - docker
before_install:
  - docker build -t mikesmithson/docker-reactjs -f Dockerfile.dev .
script:
  - docker run -e CI=true mikesmithson/docker-reactjs npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-reactjs"
  env: "DockerReactjs-env"
  bucket_name: "elasticbeanstalk-us-east-2-411744094324"
  bucket_path: "docker-reactjs"
  on:
    branch: master